jobs:
  include:
  - stage: GitHub Release
    script: "./build.sh"
    deploy:
      provider: releases
      api_key:
        secure: B6zvfCk0J+E9t7VBapmQsVNf7A8iBwA/KjsLou3NCZTMENjszyb4rKEMpVJohxnmM/qGsA/BynBX94bHMAdh0POBAa3qB9d7KBi9hccFl+jKisL415PmTs4dhDwhawn+vGqt2gNcJH1J21XTgLF7YTD7Pwsi2o+AU7gTszdKpt3xOTlAx8IKIjZQypjiuHIa0dSMzOeKctsuszctDu1GZSJjjaudSSgvv1iU087JVQqQJQw2fP7oOruMO0OfhPB3FILfZLHd3m/nTPMLAEi3NHR4P7jY3mj+WHUhwGV9BB5xuOyWXw/uhaw5Inusee4leXpyV1/DaMMXqkyJS3vMCSoQcJ3zlUP7O/LmCOu03Xc5MbaVfpxAObHqaaUScsl8NHkPytIRvY56mDVxmVPnUBXnRb4Epk3iLa/+S1e5On5+iTcdGlT5O1w+XQyUJaCa3/XNrYLkaUESlldEbXW8TEbRyZVRr+DNbcsCj/fKrteqWbIdPFPs3hm2OWZ++HfXkwEAmU+HFAH73CUUs/7+R16ZnPELH+3rUtZz7b4uL72mpucxX5boscVZvccGaG39o6rYAW4eS8RkUSFzpxj2jEvHgsg86nbCPH489XHYeRez1p08DBMQOZeywol3mpQlTpf9zbtCnj1z66FaW08zRPhleOhh/DJMdoOxcZzaYQ4=
      file_glob: true
      file: dist/*.miz
      on:
        repo: brettswift/dcs-missions
        tags: true
        all_branches: true
      skip_cleanup: true
